<html><head>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.3/dist/chart.umd.min.js"></script>
</head>
<body>
<h1>숫자 맞추기</h1>
<div id="mydiv">1부터 100 사이의 숫자 입력</div>
<input id="datain">
<button onclick="my()">확인</button>
<canvas id="mychart"></canvas>
<script>
answer = Math.floor(Math.random()*100) + 1;   alert(answer)
mydiv = document.querySelector("#mydiv");  num = document.querySelector("#datain")
try_num = 0; MAX_TRY = 10
num_in = []; ans_data = [], lables = []
function my() {
    //mydiv.innerHTML += "<br>입력 값은 " + num.value
    inum = Number(num.value)
    if ( inum <= 0 ) {  mydiv.innerHTML += "<br>숫자를 입력하세요.";  return    }
    num_in[try_num] = inum;  lables[try_num] = try_num+1;  ans_data[try_num] = answer
    try_num++
    if ( answer == inum ) {
        mydiv.innerHTML += "<br>정답입니다." + try_num + "번에 맞추었습니다." 
        mydiv.innerHTML += "<br>입력 데이터 : " + num_in + lables + ans_data
        makechart()
        return
    }
    if ( try_num == MAX_TRY ) {
        mydiv.innerHTML += "<br>맞추기 실패. 최대 횟수 " + try_num + "에 도달했습니니다.";   return
    }
    if ( answer < inum ) {
        mydiv.innerHTML += "<br>더 적은 값을 찾으세요. 현재 " + try_num + "번째 시도했음"
        num.value = ""
    } else if ( answer > inum ) {
        mydiv.innerHTML += "<br>더 큰 값을 찾으세요. 현재 " + try_num + "번째 시도했음"
        num.value = ""
    }
}
function makechart() {
     //alert("makechart")
     datainfo = { labels : lables,
                      datasets : [ {
                           label : "answer",
                           backgroundColor : [ 'gray', 'red' ],  borderColor : 'blue',
                           data : ans_data, tension : 0.5
                         },
                         {
                           label : "input data", 
                           backgroundColor : [ 'gray', 'green' ],  borderColor : 'red',
                           data : num_in, tension : 0.5
                         }
                      ]
      }
     config = { type : "line", data : datainfo, options: {} }
     new Chart(document.querySelector("#mychart"), config)
}
</script>
</body></html>
